---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: sneakstore
spec:
  selector:
    app: auth
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: sneakstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sre3-auth-service-tf:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: sneakstore
spec:
  selector:
    app: product
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: sneakstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: sre3-product-service-tf:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: sneakstore
spec:
  selector:
    app: order
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: sneakstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: sre3-order-service-tf:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: sneakstore
spec:
  selector:
    app: user
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: sneakstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: sre3-user-service-tf:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: sneakstore
spec:
  selector:
    app: inventory
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: sneakstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: sre3-inventory-service-tf:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: sneakstore
spec:
  selector:
    app: recommendation
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  namespace: sneakstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
        - name: recommendation
          image: sre3-recommendation-service-tf:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
